#TODO: добавить контейнер сервера
version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - '5460:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=test
